---
title: "DataExploration_DG2019"
author: "Kathleen Mason"
date: "4/13/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Getting Setup}
library(tidyverse)

getwd()

Duck<-read.csv("./Processed/DG2019_DuckPond_processed.csv")
Upper<-read.csv("./Processed/DG2019_UpperPond_processed.csv")
South<-read.csv("./Processed/DG2019_SouthPond_processed.csv")
```

```{r Examining Dimensions and Setup of Data}
head(Duck)
dim(Duck)

head(Upper)
dim(Upper)

head(South)
dim(South)
#South Pond has one less row because March had been removed because there was no data
```

```{r Changing Column Headings}

colnames(Duck)<-c("Month", "FOP", "TP", "NOx", "NHx", "TN", "TSS", "FecalColiform", "TC", "O Saturation", "OConcentration", "Sp.Conductivity", "Elec.Conductivity", "TDS", "Salinity", "pH", "MonthNumber")
write.csv(Duck, row.names = FALSE, file = ("./Processed/DG2019_DuckPond_processed.csv"))

colnames(South)<-c("Month", "FOP", "TP", "NOx", "NHx", "TN", "TSS", "FecalColiform", "TC", "OSaturation", "OConcentration", "Sp.Conductivity", "Elec.Conductivity", "TDS", "Salinity", "pH", "MonthNumber")
write.csv(South, row.names = FALSE, file = ("./Processed/DG2019_SouthPond_processed.csv"))

colnames(Upper)<-c("Month", "FOP", "TP", "NOx", "NHx", "TN", "TSS", "FecalColiform", "TC", "OSaturation", "OConcentration", "Sp.Conductivity", "Elec.Conductivity", "TDS", "Salinity", "pH", "MonthNumber")
write.csv(Upper, row.names = FALSE, file = ("./Processed/DG2019_UpperPond_processed.csv"))
```


```{r }
#Duck
ggplot(Duck) +
  geom_histogram(aes(x = TP))

ggplot(Duck)+
geom_freqpoly(aes(x = TP))

ggplot(Duck)+
  geom_boxplot(aes(x=TP, y=TN)) #this one isn't a good visualization

#scatterplot will probably be the best visualization plot
ggplot(Duck) +
  geom_point(aes(x = TP, y = TN ))
ggplot(Duck) +
  geom_point(aes(x =MonthNumber, y = TP))
```

I want rain data so I can properly analyze precipitations impacts on these nutrients. There is a parking lot that allows runoff into these ponds. Does rain have an impact on the concentration of nutrients in Duke Garden Ponds?***
```{r Obtaning and Wrangling Rain Data}
Rain<-read.csv("./Raw/RainStation.csv")
Rain$DATE <- as.Date(Rain$DATE, format = "%Y-%m-%d")
class(Rain$DATE)
#create a column for month using the DATE
Rain[, "Month"] <- format(Rain[,"DATE"], "%m")

#Now I need to find the mean of precipitation for each month
RainMonthlyMeans<-aggregate(PRCP ~ Month, Rain , mean )
#Leaves month number and mean precipitation for each month at that one sampling gage station



```

```{r Prepping for Analysis}
#selecting columns of interest for analysis
Duck.subset<- select(Duck, Month,TP:FecalColiform,TDS:MonthNumber)
#Need to add column of Pond Name if going to combine datasets into one
Duck.subset$PondName<- c("Duck")


South.subset<- select(South, Month,TP:FecalColiform,TDS:MonthNumber)
South.subset$PondName<- c("South")

Upper.subset<- select(Upper, Month,TP:FecalColiform,TDS:MonthNumber)
Upper.subset$PondName<- c("Upper")

DGPonds<- full_join(Duck.subset, South.subset)
DGPonds2019<-full_join(DGPonds, Upper.subset)

write.csv(DGPonds2019, row.names = FALSE, file = ("./Processed/DG2019_AllPonds_processed.csv"))
```



```{r Giving DGPonds2019 A Real Date}
Date<-c("01/01", "02/01", "03/01", "04/01", "05/01", "06/01", "07/01", "08/01", "09/01", "10/01", "11/01", "12/01", "01/01", "02/01", "04/01", "05/01", "06/01", "07/01", "08/01", "09/01", "10/01", "11/01", "12/01", "01/01", "02/01", "03/01", "04/01", "05/01", "06/01", "07/01", "08/01", "09/01", "10/01", "11/01", "12/01")
DGPonds2019$Date<-Date
DGPonds2019$Date <- as.Date(DGPonds2019$Date, format = "%m/%d")
#Now it is in a real date format, but the year is 2020, which is wrong, the year should be 2019
DGPonds2019$Month <- format(as.Date(DGPonds2019$Date), "%m")
class(DGPonds2019$Month3)
```

```{r One Rain Dataset for every Pond}
RainDuck<-RainMonthlyMeans

RainSouth<-RainMonthlyMeans
RainSouth$PondName<- c("South")
#South Pond doesn't have march, maybe we should delete it now so if we combin datasets it doesn't cause problems
RainSouth <- RainSouth[-c(3),] 

RainUpper<-RainMonthlyMeans
RainUpper$PondName<- c("Upper")

#combine rain for each pond
AllRain1<-full_join(RainDuck, RainSouth)
AllRain<-full_join(AllRain1, RainUpper)

```


```{r Combine Rain and WQ}

DGRainWQ<-full_join(AllRain, DGPonds2019)


#SUCCESS

write.csv(DGRainWQ, row.names = FALSE, file = ("./Processed/DG2019_RainandWQ_processed.csv"))
```


```{r All Ponds Visualization}
ggplot(DGPonds2019) +
  geom_point(aes(x = MonthNumber, y = TP, color = PondName))

ggplot(DGPonds2019) +
  geom_point(aes(x = MonthNumber, y = TN))+
  facet_wrap(vars(PondName), nrow = 3)
#We can see that TN is highest for all ponds at month 5, and the highest in Duck Pond

ggplot(DGPonds2019) +
  geom_point(aes(x = MonthNumber, y = TSS))+
  facet_wrap(vars(PondName), nrow = 3)

ggplot(DGPonds2019) +
  geom_point(aes(x = MonthNumber, y = NHx))+
  facet_wrap(vars(PondName), nrow = 3)


```
