---
title: "DataWrangling_DG2019"
author: "Environmental Data Analytics Course Project- Kathleen Mason"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r Setting Up, message = FALSE}
getwd()
library(dplyr)
library(tidyr)
library(tidyverse)


#Uploading Data

Duck<-read.csv("./Raw/DG2019_DuckPond_raw.csv")
Upper<-read.csv("./Raw/DG2019_UpperPond_raw.csv")
South<-read.csv("./Raw/DG2019_SouthPond_raw.csv")



```

#Data wrangling Duck Pond
```{r Duck Pond Wrangling, message = FALSE}
#We want the means of the three replicates for each month
Duck_Means<-aggregate(Duck, by=list(Duck$Month), FUN = mean)

Duck_Means<- Duck_Means %>% select(Group.1, FOP..µg.L.: Fecal.Coliform) 
names(Duck_Means)[1]<-paste("Month")
Duck_Means<-na.omit(Duck_Means) #omitting NAs

#need to name the column that has month names but is called GRoup.1- needs to be month or date?

class(Duck_Means$Group.1)
names(Duck_Means)[1]<-"Month"

#YSI data no longer in same dataset, now need to add it back

#First select only Month and rep 1 from Duck, so we only obtain the ysi data
Duck_YSI<-filter(Duck, Rep== "Rep1")
#Now select only YSI columns and month names
Duck_YSI<-Duck_YSI %>% select(Month, T...C.: pH)


#We can join the YSI data and the parameters by month name

Duck_Compilation<- full_join(Duck_Means, Duck_YSI)

#Done! YAY!
```

```{r South Pond Data Wrangling}
#We want the means of the three replicates for each month
South_Means<-aggregate(South, by=list(South$Month), FUN = mean)

South_Means<- South_Means %>% select(Group.1, FOP..µg.L.: Fecal.Coliform) 
names(South_Means)[1]<-paste("Month")
South_Means<-na.omit(South_Means) #omitting NAs



#YSI data no longer in same dataset, now need to add it back

#First select only Month and rep 1 from Duck, so we only obtain the ysi data
South_YSI<-filter(South, Rep== "Rep1")
#Now select only YSI columns and month names
South_YSI<-South_YSI %>% select(Month, T...C.: pH)
South_YSI<-na.omit(South_YSI)

#We can join the YSI data and the parameters by month name

South_Compilation<- full_join(South_Means, South_YSI)

#Done! YAY!



```


```{r Upper Pond Data Wrangling}
#We want the means of the three replicates for each month
Upper_Means<-aggregate(Upper, by=list(Upper$Month), FUN = mean)

Upper_Means<- Upper_Means %>% select(Group.1, FOP..µg.L.: Fecal.Coliform) 
names(Upper_Means)[1]<-paste("Month")
Upper_Means<-na.omit(Upper_Means) #omitting NAs



#YSI data no longer in same dataset, now need to add it back

#First select only Month and rep 1 from Duck, so we only obtain the ysi data
Upper_YSI<-filter(Upper, Rep== "Rep1")
#Now select only YSI columns and month names
Upper_YSI<-Upper_YSI %>% select(Month, T...C.: pH)
Upper_YSI<-na.omit(Upper_YSI)

#We can join the YSI data and the parameters by month name

Upper_Compilation<- full_join(Upper_Means, Upper_YSI)
Upper_Compilation<-na.omit(Upper_Compilation)
```

```{r Changing Month Names}

#Duck
Duck_Compilation<-edit(Duck_Compilation) #made all in three letter format

#Trying to figure out how to convert the factor into a date
#class(Duck_Compilation$Month)
#Duck_Compilation$Month1<-match(Duck_Compilation$Month,month.abb)
#class(Duck_Compilation$Month1)
#Duck_Compilation$Month<-as.Date(Duck_Compilation$Month, format = "%B")
#Kept changing Month to all NAs, so we will continue with Month as a factor for now


#still need to put months in the correct order, since I can;t figure out how to convert the real Month column to date, I will still make the other column of month # corresponding to the Month column, and then use this to reorder the rows so they are in the proper month order
#Creating the month # column named Month1
Duck_Compilation$Month1<-match(Duck_Compilation$Month,month.abb)
#Reorder rows by Month1 or the month #s
head(Duck_Compilation[order(Duck_Compilation$Month1), ])

#This works correctly so now let's apply it to our data frame
Duck_Compilation<- Duck_Compilation[order(Duck_Compilation$Month1), ]
#YES!
write.csv(Duck_Compilation, row.names = FALSE, file = ("./Processed/DG2019_DuckPond_processed.csv"))


#South
South_Compilation<-edit(South_Compilation) #made all in three letter format
South_Compilation$Month1<-match(South_Compilation$Month,month.abb)
South_Compilation<- South_Compilation[order(South_Compilation$Month1), ]

write.csv(South_Compilation, row.names = FALSE, file = ("./Processed/DG2019_SouthPond_processed.csv"))

#Upper
Upper_Compilation<-edit(Upper_Compilation) #made all in three letter format
Upper_Compilation$Month1<-match(Upper_Compilation$Month,month.abb)
Upper_Compilation<- Upper_Compilation[order(Upper_Compilation$Month1), ]

write.csv(Upper_Compilation, row.names = FALSE, file = ("./Processed/DG2019_UpperPond_processed.csv"))


```


