---
title: "DataVisualization_DG2019"
author: "Kathleen Mason"
date: "4/13/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Getting Set Up}
getwd()

library(tidyverse)
library(viridis)

#Read in processed file
DGRainWQ<-read.csv("./Processed/DG2019_RainandWQ_processed.csv")
class(DGRainWQ$MonthNumber)


#Make sure month column is working properly
DGRainWQ$Date <- as.Date(DGRainWQ$Date, format = "%Y-%m-%d")
DGRainWQ[, "MonthNumber"] <- format(DGRainWQ[,"Date"], "%m")
DGRainWQ$MonthNumber<-as.Date(DGRainWQ$MonthNumber, format = "%m")
class(DGRainWQ$MonthNumber)
```

```{r Theme}
mytheme <- theme_light(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)
```

```{r }
FecalvsO <-
  ggplot(DGRainWQ, aes(x = FecalColiform, y = OConcentration, color = PondName)) +
  geom_point() 
print(FecalvsO)


PvsTN <-
  ggplot(DGRainWQ, aes(x = PRCP, y = TN, color = PondName)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "black")
print(PvsTN)
#I was expecting higher TN and TP with more precipitation, but in fact I am getting the opposite...awesome
 
ggplot(DGRainWQ) +
  geom_point(aes(x = OConcentration, 
                 y = FecalColiform))+
  facet_wrap(vars(PondName), nrow=3)


ggplot(DGRainWQ) +
  geom_point(aes(x = TP, 
                 y = MonthNumber), color = PondName)
```


