---
title: "Data Wrangling"
author: "Environmental Data Analytics Course Project- Kathleen Mason"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r Setting Up, message = FALSE}
getwd()
library(dplyr)
library(tidyr)


#Uploading Data
WQ<- read.csv("./Raw/DG2019_WQTests_raw.csv")
YSI<-read.csv("./Raw//DG2019_YSI_raw.csv")
Duck<-read.csv("./Raw/DuckPond_R.csv")
Upper<-read.csv("./Raw/UpperPond_R.csv")
South<-read.csv("./Raw/SouthPool_R.csv")

#Changing dates for R to acknowledge they are dates
class(YSI$Date)
#YSI dataset dates were integers previously, now they are correct dates
YSI <- transform(YSI, Date = as.Date(as.character(Date), "%Y%m%d"))

class(WQ$Collection.Date)

#Collection date listed as DG_20190110_SW, need to break this apart into 3 different collumns
WQ_NewDate<- WQ %>% separate(Collection.Date, 
                c("ID", "Date", "Testing Type"))
#Now the Date column needs to be formatted correctly

WQ_NewDate <- transform(WQ_NewDate, Date = as.Date(as.character(Date), "%Y%m%d"))

class(WQ_NewDate$Date)

#Save altered data sets in processed folder
write.csv(YSI, row.names = FALSE, file = "./Processed/DG2019_YSIdata_processed.csv")

write.csv(WQ_NewDate, row.names = FALSE, file = "./Processed/DG2019_WQdata_processed.csv")

#There are NA's on a particular date because construction was happening, but we will remove these so they don't mess up our data later. I will name this something different in case we need to go back to dataframe with NA's still included
#Omit NA's
WQ_NoNA <- na.omit(WQ_NewDate)


```

#Data wrangling Duck Pond
```{r Duck Pond Wrangling, message = FALSE}
#We want the means of the three replicates for each month
Duck_Means<-aggregate(Duck, by=list(Duck$Month), FUN = mean)

Duck_Means<- Duck_Means %>% select(Group.1, FOP..µg.L.: Fecal.Coliform) 
names(Duck_Means)[1]<-paste("Month")
Duck_Means<-na.omit(Duck_Means) #omitting NAs

#need to name the column that has month names but is called GRoup.1- needs to be month or date?

class(Duck_Means$Group.1)
class(Duck_YSI$Month)
names(Duck_Means)[1]<-"Month"

#YSI data no longer in same dataset, now need to add it back

#First select only Month and rep 1 from Duck, so we only obtain the ysi data
Duck_YSI<-filter(Duck, Rep== "Rep1")
#Now select only YSI columns and month names
Duck_YSI<-Duck_YSI %>% select(Month, T...C.: pH)


#We can join the YSI data and the parameters by month name

Duck_Compilation<- full_join(Duck_Means, Duck_YSI)

#Done! YAY!
```

```{r South Pond Data Wrangling}
#We want the means of the three replicates for each month
South_Means<-aggregate(South, by=list(South$Month), FUN = mean)

South_Means<- South_Means %>% select(Group.1, FOP..µg.L.: Fecal.Coliform) 
names(South_Means)[1]<-paste("Month")
South_Means<-na.omit(South_Means) #omitting NAs



#YSI data no longer in same dataset, now need to add it back

#First select only Month and rep 1 from Duck, so we only obtain the ysi data
South_YSI<-filter(South, Rep== "Rep1")
#Now select only YSI columns and month names
South_YSI<-South_YSI %>% select(Month, T...C.: pH)
South_YSI<-na.omit(South_YSI)

#We can join the YSI data and the parameters by month name

South_Compilation<- full_join(South_Means, South_YSI)

#Done! YAY!



```


```{r Upper Pond Data Wrangling}
#We want the means of the three replicates for each month
Upper_Means<-aggregate(Upper, by=list(Upper$Month), FUN = mean)

Upper_Means<- Upper_Means %>% select(Group.1, FOP..µg.L.: Fecal.Coliform) 
names(Upper_Means)[1]<-paste("Month")
Upper_Means<-na.omit(Upper_Means) #omitting NAs



#YSI data no longer in same dataset, now need to add it back

#First select only Month and rep 1 from Duck, so we only obtain the ysi data
Upper_YSI<-filter(Upper, Rep== "Rep1")
#Now select only YSI columns and month names
Upper_YSI<-Upper_YSI %>% select(Month, T...C.: pH)
Upper_YSI<-na.omit(Upper_YSI)

#We can join the YSI data and the parameters by month name

Upper_Compilation<- full_join(Upper_Means, Upper_YSI)
Upper_Compilation<-na.omit(Upper_Compilation)
```

```{r Yearly Means}

DuckYMeans<-Duck_Compilation %>% summarise_if(is.numeric, mean)
SouthYMeans<-South_Compilation %>% summarise_if(is.numeric, mean)
UpperYMeans<-Upper_Compilation %>% summarise_if(is.numeric, mean)

DuckYMeans$Site<-c("Duck Pond")
SouthYMeans$Site<-c("South Pond")
UpperYMeans$Site<-c("Upper Pond")

#AllMeans2019<-rbind(DuckYMeans, SouthYMeans)
#AllMeans2019<-rbind(AllMeans2019, UpperYMeans)
#For some reason names in Upper Pond data are different than the other 2 pond data sets

Table1_Duck<-DuckYMeans %>% select(TP..µg.L., TN..µg.L., TSS..mg.L. ,Fecal.Coliform, pH)
Table1_South<- SouthYMeans %>% select(TP..µg.L., TN..µg.L., TSS..mg.L. ,Fecal.Coliform, pH)
Table1_Upper<- UpperYMeans %>% select(TP..µg.L., TN..µg.L., TSS..mg.L. ,Fecal.Coliform, pH)
```

```{r Graphs}
library(tidyverse)

ggplot(Duck_Means, aes(x = Month, y = TP..µg.L. )) + 
  geom_point() 

ggplot(Upper_Means, aes(x = Month, y = TP..µg.L. )) + 
  geom_point() 

ggplot(South_Means, aes(x = Month, y = TP..µg.L. )) + 
  geom_point() 

```

