---
title: "Initial Steps"
author: "Environmental Data Analytics Course Project- Kathleen Mason"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
getwd()
library(dplyr)
library(tidyr)


#Uploading Data
WQ<- read.csv("./Raw/DG2019_WQTests_raw.csv")
YSI<-read.csv("./Raw//DG2019_YSI_raw.csv")
Duck<-read.csv("./Raw/DuckPond_R.csv")
Upper<-read.csv("./Raw/UpperPond_R.csv")
South<-read.csv("./Raw/SouthPool_R.csv")

#Changing dates for R to acknowledge they are dates
class(YSI$Date)
#YSI dataset dates were integers previously, now they are correct dates
YSI <- transform(YSI, Date = as.Date(as.character(Date), "%Y%m%d"))

class(WQ$Collection.Date)

#Collection date listed as DG_20190110_SW, need to break this apart into 3 different collumns
WQ_NewDate<- WQ %>% separate(Collection.Date, 
                c("ID", "Date", "Testing Type"))
#Now the Date column needs to be formatted correctly

WQ_NewDate <- transform(WQ_NewDate, Date = as.Date(as.character(Date), "%Y%m%d"))



#Save altered data sets in processed folder
write.csv(YSI, row.names = FALSE, file = "./Processed/DG2019_YSIdata_processed.csv")

write.csv(WQ_NewDate, row.names = FALSE, file = "./Processed/DG2019_WQdata_processed.csv")

#There are NA's on a particular date because construction was happening, but we will remove these so they don't mess up our data later. I will name this something different in case we need to go back to dataframe with NA's still included
#Omit NA's
WQ_NoNA <- na.omit(WQ_NewDate)


```

#Data wrangling Duck Pond
```{r, message = FALSE}
#We want the means of the three replicates for each month
Duck_Means<-aggregate(Duck, by=list(Duck$Month), FUN = mean)

Duck_Means<- Duck_Means %>% select(Group.1, FOP..µg.L.: Fecal.Coliform) 
names(Duck_Means)[1]<-paste("Month")

#YSI data no longer in same dataset, now need to add it back

#First select only Month and rep 1 from Duck, so we only obtain the ysi data
Duck_YSI<-filter(Duck, Rep== "Rep1")
#Now select only YSI columns and month names
Duck_YSI<-Duck_YSI %>% select(Month, T...C.: pH)


#We can join the YSI data and the parameters by month name

Duck_Compilation<- full_join(Duck_Means, Duck_YSI)

#There is a random row 1 with NAs, lets drop this
Duck_Compilation<-Duck_Compilation[-c(1),]
#Gone!
```
