---
title: "Test"
author: "Kathleen Mason"
date: "4/18/2020"
output: html_document
---

```{r Yearly Means}

DuckYMeans<-Duck_Compilation %>% summarise_if(is.numeric, mean)
SouthYMeans<-South_Compilation %>% summarise_if(is.numeric, mean)
UpperYMeans<-Upper_Compilation %>% summarise_if(is.numeric, mean)

DuckYMeans$Site<-c("Duck Pond")
SouthYMeans$Site<-c("South Pond")
UpperYMeans$Site<-c("Upper Pond")

#AllMeans2019<-rbind(DuckYMeans, SouthYMeans)
#AllMeans2019<-rbind(AllMeans2019, UpperYMeans)
#For some reason names in Upper Pond data are different than the other 2 pond data sets

Table1_Duck<-DuckYMeans %>% select(TP..µg.L., TN..µg.L., TSS..mg.L. ,Fecal.Coliform, pH)
Table1_South<- SouthYMeans %>% select(TP..µg.L., TN..µg.L., TSS..mg.L. ,Fecal.Coliform, pH)
Table1_Upper<- UpperYMeans %>% select(TP..µg.L., TN..µg.L., TSS..mg.L. ,Fecal.Coliform, pH)
```

```{r Graphs}
library(tidyverse)

ggplot(Duck_Means, aes(x = Month, y = TP..µg.L. )) + 
  geom_point() 

ggplot(Upper_Means, aes(x = Month, y = TP..µg.L. )) + 
  geom_point() 

ggplot(South_Means, aes(x = Month, y = TP..µg.L. )) + 
  geom_point() 

```


```

